baseURL = "https://shengjie77.github.io/blog/"
languageCode = "en-us"
title = "Sheng Jie's blog"
theme = "yinyang"
publishDir = "docs"

[author]
    name = "Sheng Jie"

[params]
    disqus = "ShengJie"
